# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NeuroSquad.NeuroSquad
PackageVersion: 0.1.148
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --dir "<INSTALLPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 2
  ReturnResponse: packageInUse
UpgradeBehavior: install
ProductCode: NeuroSquad
ReleaseDate: 2026-09-27
AppsAndFeaturesEntries:
- DisplayName: NeuroSquad
  Publisher: NeuroSquad
  ProductCode: NeuroSquad
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/glmn-ai/neurosquad-releases/releases/download/v0.1.148/NeuroSquad-Setup.exe
  InstallerSha256: 4CA419A0BCB09A8AEB7F437545DE4C0A6AC70238BC5C35E7C4E1845367A85038
ManifestType: installer
ManifestVersion: 1.12.0
