# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: NeuroSquad.NeuroSquad
PackageVersion: 0.1.270
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
  InstallLocation: --dir "<INSTALLPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 2
  ReturnResponse: packageInUse
UpgradeBehavior: install
ProductCode: NeuroSquad
ReleaseDate: 2026-10-05
AppsAndFeaturesEntries:
- DisplayName: NeuroSquad
  Publisher: NeuroSquad
  ProductCode: NeuroSquad
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/glmn-ai/neurosquad-releases/releases/download/v0.1.270/NeuroSquad-Setup.exe
  InstallerSha256: FC189FCB6B0ED4E7F742B82D981C97E47D67C8495FCE555721ABE343ED130EC1
ManifestType: installer
ManifestVersion: 1.12.0
